In [1]:
import torch
import torch.nn as nn

In [2]:
input_tensor = torch.tensor(
    [[0.3471, 0.4547, -0.2356]]
)

In [3]:
linear_layer = nn.Linear(
    in_features=3,
    out_features=2
)

In [4]:
output = linear_layer(input_tensor)
output

tensor([[-0.1517,  0.4693]], grad_fn=<AddmmBackward0>)

In [5]:
linear_layer.weight

Parameter containing:
tensor([[-0.4010,  0.1062,  0.0039],
        [ 0.4120,  0.4155,  0.4003]], requires_grad=True)

### Capas secuenciales

In [6]:
model = nn.Sequential(
    nn.Linear(10, 15),
    nn.Linear(15, 5),
    nn.Linear(5, 3)
)

## Activation functions

- Sigmoid (binary)

In [10]:
input_tensor = torch.tensor([[1.0]])
sigmoid = nn.Sigmoid()
sigmoid(input_tensor)

tensor([[0.7311]])

In [11]:
model_2 = nn.Sequential(
    nn.Linear(6,4),
    nn.Linear(4,1),
    nn.Sigmoid()
)

- Softmax (multiclass)

In [12]:
input_tensor = torch.tensor([[4.3, 6.1, 2.3]])

probabilities = nn.Softmax(dim=-1)
probabilities(input_tensor)

tensor([[0.1392, 0.8420, 0.0188]])